# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: D4D Coalition
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Design 4 Democracy Coalition is a multi-partisan, global grouping of key actors in the democracy community to better liaise and coordinate with tech companies and social media platforms on matters of shared concern.
baseurl: "" # the subpath of your site, e.g. /blog


# Theme Settings
relativity:
  date_format: "%b %-d, %Y"

# SEO Meta - global settings
lang: en_US
url: "https://d4dcoalition.org" # the base hostname & protocol for your site
author: ""
logo: ""
social:
  links:
    twitter: https://twitter.com/design4dem
    facebook: https://www.facebook.com/Design4Democracy

# Twitter card defaults
twitter:
  username: design4dem
  card: summary

# Collections
collections_dir: collections
collections:
  bios:
    output: true
    permalink: /advisory-board/:title.html
  news:
    output: true
    permalink: /:collection/:title.html
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "bios"
    values:
      layout: "bio"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  #sourcemap: true
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
